### ISSUE TITLE
3rd Kline

### ISSUE THREAD

**Issue by ChannelSave** [pragma-/pbot#56]
Gather information to get reasons for development purposes.

**Comment by ChannelSave** [comment]
Hello,

 

https://hastebin.com/enowosodot.http

 

This account was banned. Unfortunately there is no usable information in the Ban Reason. This perl process was currently in a test run to determine errors in connection with the sq3 database. For this reason, the developer - I am in contact with - is very interested in the reason for the forced termination. It is also important what exactly the process did or posted. Perhaps an error message was sent in a foreign channel that would contain an error code.


 

 

Thank you in advance for processing.

**Comment by pragma-** [comment]
For clarification to anybody reading this issue: ChannelSave connected PBot to the Freenode IRC network and joined over 60 very public and very large channels. He was eventually klined.

He informed me of it and I asked him for the kline reason. I suggested that he e-mail Freenode support to obtain the reason. He opened this issue to attach it to the e-mail.

This isn't necessary. Instead of deleting this issue I am going to simply close it, as to not break the e-mail to Freenode support.

If the reason for ChannelSave's kline turns out to be related to a PBot-specific issue -- rather than due to the way ChannelSave has configured his PBot instance, I will re-open and update this issue.
